@MyFirstDotnetApi_HostAddress = http://localhost:5012

### Health check
GET {{MyFirstDotnetApi_HostAddress}}/ping
Accept: application/json

### GET users
GET http://localhost:5012/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOTRmMDUxZS1hMDcwLTQxYjYtOGRjYy0xYTY0NDZmMmVjZWYiLCJqdGkiOiI2YWU2YTUzNS1iOWY2LTQwMzktOGRkNy04YjVkMmY2ZTRhMWQiLCJleHAiOjE3NDMwOTM3OTEsImlzcyI6Ik15Rmlyc3REb3RuZXRBcGkiLCJhdWQiOiJNeUZpcnN0RG90bmV0QXBpVXNlcnMifQ.iFRhDHR6rEe0bJnHs2eBU9qhBk9lPDVS4avCp6as_dM
Accept: application/json

### POST user
POST http://localhost:5012/users
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Johnson",
  "email": "alice@example.com",
  "phoneNumber": "+123456789"
}

### GET user by id
GET http://localhost:5012/users/c21fedc6-0207-4889-8c87-bfbd54f87494
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOTRmMDUxZS1hMDcwLTQxYjYtOGRjYy0xYTY0NDZmMmVjZWYiLCJqdGkiOiI2YWU2YTUzNS1iOWY2LTQwMzktOGRkNy04YjVkMmY2ZTRhMWQiLCJleHAiOjE3NDMwOTM3OTEsImlzcyI6Ik15Rmlyc3REb3RuZXRBcGkiLCJhdWQiOiJNeUZpcnN0RG90bmV0QXBpVXNlcnMifQ.iFRhDHR6rEe0bJnHs2eBU9qhBk9lPDVS4avCp6as_dM
Accept: application/json

### Update user by id
PUT http://localhost:5012/users/c21fedc6-0207-4889-8c87-bfbd54f87494
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Smith",
  "email": "bob@example.com",
  "phoneNumber": "+1987654321"
}

### DELETE user by id
DELETE http://localhost:5012/users/c21fedc6-0207-4889-8c87-bfbd54f87494
Accept: application/json

### New user registration
POST http://localhost:5012/auth/register
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Smith",
  "email": "bob@example.com",
  "phoneNumber": "+1987654321",
  "password": "qwerty"
}

### User login
POST http://localhost:5012/auth/login
Content-Type: application/json

{
  "email": "bob@example.com",
  "password": "qwerty"
}