@MyFirstDotnetApi_HostAddress = http://localhost:5012

### Health check
GET {{MyFirstDotnetApi_HostAddress}}/ping
Accept: application/json

### GET users
GET http://localhost:5012/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYTcwZGE0ZS0yY2RiLTQwMDctOWYyMC03NmFhNTkwZmFlMTkiLCJqdGkiOiI0YzQ4OGU3MC00MDc2LTQ5YmYtYWZjMi0xNzAxOTcxNmE5MWUiLCJleHAiOjE3NDMwNzM2MzcsImlzcyI6Ik15Rmlyc3REb3RuZXRBcGkiLCJhdWQiOiJNeUZpcnN0RG90bmV0QXBpVXNlcnMifQ.UHVQQh4HQOtpAHWMI1r0FVET88_cO591uQ68x8iRBd4
Accept: application/json

### POST user
POST http://localhost:5012/users
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Johnson",
  "email": "alice@example.com",
  "phoneNumber": "+123456789"
}

### GET user by id
GET http://localhost:5012/users/c21fedc6-0207-4889-8c87-bfbd54f87494
Accept: application/json

### DELETE user by id
PUT http://localhost:5012/users/c21fedc6-0207-4889-8c87-bfbd54f87494
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Smith",
  "email": "bob@example.com",
  "phoneNumber": "+1987654321"
}

### DELETE user by id
DELETE http://localhost:5012/users/c21fedc6-0207-4889-8c87-bfbd54f87494
Accept: application/json

### New user registration
POST http://localhost:5012/auth/register
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Smith",
  "email": "bob@example.com",
  "phoneNumber": "+1987654321",
  "password": "qwerty"
}

### User login
POST http://localhost:5012/auth/login
Content-Type: application/json

{
  "email": "bob@example.com",
  "password": "qwerty"
}